spring:
  application:
    name: dayone-financial

  h2:
    console:
      enabled: true


  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mapping: false
    show-sql: true
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:dayone;DB_CLOSE_DELAY=1
    username: sa
    password:
    driverClassName: org.h2.Driver

